#!/bin/bash

fr() {
  if [ $# -eq 0 ]; then
    echo
    echo "Please run fr command again with a filename and directory"
    echo "Example: fr App.js src"
    echo
  elif [ $# -eq 1 ]; then
    echo
    echo "Please run fr command again with a filename and directory"
    echo "Example: fr App.js src"
    echo
  else
    mkdir -p $2
    find . -iname "*$1*" -type f -exec cp {} ./$2 \;
  fi
}
