#!/bin/bash
mps() {
  if [ $# -eq 0 ]; then
    fzf | xargs -I {} mpv --playlist={}
  elif [ $# -eq 1 ]; then
    fzf | xargs -I {} mpv --playlist={} --playlist-start=$(($1 - 1))
  else
    echo
    echo "Only one argument is valid for specifying the start number of the video in the playlist."
    echo
  fi
}
