#!/bin/bash

repo() {
  echo -n "What is your username? "
  read UNAME

  echo -n "What is the repo name? "
  read REPO

  echo -n "What is the repo description? "
  read DESC

  echo -n "Is this repo private? (y/n) "
  read PRIVATE

  case $PRIVATE in
    y|yes)
      private_Msg=$(curl -u "$UNAME" https://api.github.com/user/repos -d '{"name":"'"$REPO"'", "description":"'"$DESC"'", "private":"true"}' | jq --raw-output '.message')

    if [ "$private_Msg" = "null" ]; then
      echo
      echo "Private repo created at https://github.com/$UNAME/$REPO"
      echo
      git init
      echo
      git add .
      git commit -m "inital commit"
      echo
      git remote add origin https://github.com/$UNAME/$REPO.git
      sleep 1
      git push -u origin master
    else
      echo
      echo "Private repo could not be created. Please try again."
      echo
    fi
    ;;

  n|no)
    public_Msg=$(curl -u "$UNAME" https://api.github.com/user/repos -d '{"name":"'"$REPO"'", "description":"'"$DESC"'"}' | jq --raw-output '.message')

    if [ "$public_Msg" = "null" ]; then
      echo
      echo "Public repo created at https://github.com/$UNAME/$REPO"
      echo
      git init
      echo
      git add .
      git commit -m "inital commit"
      echo
      git remote add origin https://github.com/$UNAME/$REPO.git
      sleep 1
      git push -u origin master
    else
      echo
      echo "Public repo could not be created. Please try again."
      echo
    fi
    ;;
  esac
}
