#!/bin/bash

# Scripts
source ~/dotfiles/bash/d
source ~/dotfiles/bash/mkcd
source ~/dotfiles/bash/ciu
source ~/dotfiles/bash/kp
source ~/dotfiles/bash/se
source ~/dotfiles/bash/vf
source ~/dotfiles/bash/fv
source ~/dotfiles/bash/ff
source ~/dotfiles/bash/psc
source ~/dotfiles/bash/mps
